/*

 TWOBOXES.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\karld\Codes\Random\SokobanGB\res\sprites\TileSprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __twoboxes_h_INCLUDE
#define __twoboxes_h_INCLUDE

#define twoBoxesWidth 20
#define twoBoxesHeight 18
#define twoBoxesBank 0

extern const unsigned char twoBoxes[];

#endif

/* End of TWOBOXES.H */
